# Generated by Django 4.1.3 on 2023-02-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0004_movie_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watched',
        ),
    ]
