# Generated by Django 4.1.3 on 2023-02-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0005_remove_movie_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
