# Generated by Django 4.1.3 on 2023-02-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0008_alter_movie_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watched',
            field=models.CharField(default='true', max_length=50),
        ),
    ]
