# Generated by Django 4.1.3 on 2023-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0011_remove_movie_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False, verbose_name='watched'),
        ),
    ]
