# Generated by Django 4.1.3 on 2023-02-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0012_movie_watched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='commentary',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watched',
        ),
    ]
